# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 17:37
from __future__ import unicode_literals

import account_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_auto_20180522_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=account_app.models.get_file_path),
        ),
    ]
