# Generated by Django 2.0.3 on 2018-05-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180521_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
