# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 11:15
from __future__ import unicode_literals

import account_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=account_app.models.get_file_path)),
                ('comment', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
