# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-26 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20180526_1540'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatingTime',
            new_name='WaitingTime',
        ),
    ]
