# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-26 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_auto_20180527_0413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaitingTime',
        ),
    ]
